assets: assets
cache: cache
discord_templates: templates\discord_templates
dreamscape_memory: memory\dreamscape
dreamscape_templates: templates\dreamscape
episodes: episodes
logs: logs
memory: memory
message_templates: templates\message_templates
metrics: metrics
outputs: outputs
project_root: .
rate_limits: cache\rate_limits
reinforcement_logs: logs\reinforcement
reports: reports
resonance_models: assets\resonance_models
social_logs: logs\social
templates: templates
tests: tests
utils_logs: logs\utils
