assets: assets
cache: cache
config: config
core: core
data: data
discord_templates: templates/discord_templates
dreamscape_memory: memory/dreamscape
dreamscape_templates: templates/dreamscape
episodes: episodes
interfaces: interfaces
logs: logs
memory: memory
message_templates: templates/message_templates
metrics: metrics
output: output
outputs: outputs
project_root: .
rate_limits: cache/rate_limits
reinforcement_logs: logs/reinforcement
reports: reports
resonance_models: core/meredith/models/
schemas: core/schemas/
social_logs: logs/social
templates: templates
tests: tests
utils_logs: logs/utils
cursor_prompts: cursor_prompts/
chrome_profile: C:/Users/USER/AppData/Local/Google/Chrome/User Data/Default
cookies: cache/browser_cookies/
