project_root: "."
templates: "templates"
cache: "cache"
logs: "logs"
metrics: "metrics"
outputs: "outputs"
episodes: "episodes"
memory: "memory"
assets: "assets"
reports: "reports"
tests: "tests"
reinforcement_logs: "logs/reinforcement"
social_logs: "logs/social"
utils_logs: "logs/utils"
rate_limits: "cache/rate_limits" 